hitas_application_created_subject_fi: 'HITAS hakemus vastaanotettu'
hitas_application_created_text_fi: 'Olemme vastaanottaneet hakemuksenne HITAS-kohteeseen.'
haso_application_created_subject_fi: 'HASO hakemus vastaanotettu'
haso_application_created_text_fi: 'Olemme vastaanottaneet hakemuksenne HASO-kohteeseen'
hitas_application_created_subject_en: 'HITAS application received'
hitas_application_created_text_en: 'We have received your HITAS application.'
haso_application_created_subject_en: 'HASO application received'
haso_application_created_text_en: 'We have received your HASO application'
hitas_application_created_subject_sv: 'HITAS application received'
hitas_application_created_text_sv: 'We have received your HITAS application.'
haso_application_created_subject_sv: 'HASO application received'
haso_application_created_text_sv: 'We have received your HASO application'
